### PR TITLE
Remove synchronized locking

### PR DESCRIPTION
**Pull request by rmarsch**
In exploring concurrency limiting options in our internal connect-jdbc code for Vitess client requests, we found that blocking operations at the GRPC level would hold synchronized instance locks in these places in VTGateConnection. After sharing with the SRE team, none of us were convinced this needed to be synchronized and after removing it and running load testing against a Vitess database with a branch release we didn't observe any errors.

This change would be required for the concurrency limiting to work.

### CODE REVIEW

**Comment by acharis** [comment]
hey, do you think you can open an upstream PR to more eyes on this?

**Comment by rmarsch** [comment]
> hey, do you think you can open an upstream PR to more eyes on this?

As in, open a PR for this against the vitessio version of the repo and see what they think of removing the synchronized blocks?

**Comment by acharis** [comment]
yes

**Comment by rmarsch** [comment]
https://github.com/vitessio/vitess/pull/6088

**Comment by rmarsch** [comment]
The impression I got from the comments so far on that PR is that if the client is protecting concurrent access to the `VTSession` then it accomplishes the same thing. Since our connections/sessions are maintained by the Hikari connection pool it seems we meet this requisite.

**Comment by acharis** [comment]
last i knew there were contemplations around removing hikari ... is this PR instead of that?

**Comment by rmarsch** [comment]
I don't think we can remove having a connection pool for Vitess, each VitessConnection can only handle a single transaction (I verified this as part of my testing for the whole feature work). At that point I'm not sure it's worth moving away from Hikari since its a reliable connection pool. I'm not sure if there were other motivations to move away.

**Comment by jhaber** [comment]
I think the idea would be do ditch JDBC (and VitessConnection) entirely, and just make GRPC calls directly. Ze'ev started working on this [here](https://git.hubteam.com/HubSpot/vdbi) but I think it's kind of dead

**Comment by rmarsch** [comment]
Ah the vdbi. In that case I'd say the concurrency limiting is separate from the decision to use Hikari and JDBC vs vdbi. The feature is implemented as a GRPC interceptor so it could be ported to VDBI pretty easily if/when we migrate from JDBC to vdbi.

**Comment by rmarsch** [comment]
I'm moving into a phase of beta branch deploys in QA with the work, so we can also use that as a litmus test for this change to feel more comfortable before considering a merge.

**Comment by rmarsch** [comment]
They merged https://github.com/vitessio/vitess/pull/6088 today

**Comment by rmarsch** [comment]
Just double checking we're happy with this given the upstream merge before merging

**Comment by acharis** [comment]
Yeah, if folks looked at it and are fine, then let's move forward with this.

**Pull request merged**
